# Ingress from vmalertmanager
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alertwebhook.ingress.from.local.vmalertmanager
  namespace: vmalert-ns
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
spec:
  endpointSelector:
    matchLabels:
      k8s:app.kubernetes.io/name: alertwebhook
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:app.kubernetes.io/name: vmalertmanager
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
